mrcal builds with g++ < 11
Some new basic-geometry utility functions make old compilers unhappy. Let's say
I have this:

  typedef union
  {
      struct
      {
          double x,y;
      };
      double xy[2];
  } mrcal_point2_t;
  mrcal_point2_t mrcal_point2_sub(const mrcal_point2_t a, const mrcal_point2_t b)
  {
      return (mrcal_point2_t){ .x = a.x - b.x,
                               .y = a.y - b.y };
  }

This happens on g++ <= 10:

dima@fatty:/tmp$ g++-10 -c -o tst.o tst.c
tst.c: In function ‘mrcal_point2_t mrcal_point2_sub(mrcal_point2_t, mrcal_point2_t)’:
tst.c:14:45: error: too many initializers for ‘mrcal_point2_t’
   14 |                              .y = a.y - b.y };
      |                                             ^

Since this happens only with c++ and with old compilers, I don't give the
unhappy code to the old compiler. People stuck in that world will need to
make do without these functions