mrcal.stereo_range() returns a scalar, if the input was a scalar
This fixes a regression introduced in 6f6212e740c61f9e16bcc69b1f38c6a7f5ffb6b0.
It also fixes a crash in mrcal-stereo: when interactively clicking of a point it
would say:

  TypeError: unsupported format string passed to numpy.ndarray.__format__